development:
  adapter: postgresql
  encoding: unicode
  database: movie_trivia_development
  pool: 5
  username: movie_trivia
  password: movie_trivia

test:
  adapter: postgresql
  encoding: unicode
  database: movie_trivia_test
  pool: 5
  username: movie_trivia
  password: movie_trivia
